// Shared components barrel export
export { LanguageIcon } from './LanguageIcon'
export { GithubIcon } from './GithubIcon'
export { UserProfileDropdown } from './UserProfileDropdown'
export { FilterDropdown } from './FilterDropdown'
export { GlassDropdown } from './GlassDropdown'
export { RoleGuard } from './RoleGuard'
export type { RoleGuardProps, AllowedRole } from './RoleGuard'
export { AuthGuard, AuthLoadingFallback } from './AuthGuard'
export type { AuthGuardProps } from './AuthGuard'
export { ScrollToTop } from './ScrollToTop'
